package _22_exception.sec02_exceptionhandlingsyntax.EX06_TryWithResource_2;


class A {
	String resource;
	A(String resource) {
		this.resource = resource;
	}
	
	@Override
	public void close() throws Exception {
		if (resource != null) {
			resource = null;
			System.out.println("리소스가 해제되었습니다.");
		}
	}
}



public class TryWithResource_2 {
	public static void main(String[] args) {
		
	}
}
