package _22_exception;

import java.util.Random;
import java.util.Scanner;

public class ExceptionTest5 {
	public static void main(String[] args) {
		
//		int n = (int)(Math.random() * 99) + 1;
		Random random = new Random();
		int n = random.nextInt(99) + 1;
		
		
		try (Scanner sc = new Scanner(System.in)){
			
		} catch (Exception e) {
			// TODO: handle exception
		}
		
	}
}
